import Foundation

let fieldBook: [FieldSpec] = fieldBookA + fieldBookB + fieldBookC

let fieldBookA: [FieldSpec] = [
    FieldSpec(id: "bowder_fell", name: "Bowder Fell", place: "Cumbria", terrain: "Open fell, rising ground",
              breed: "Herdwick", sheepCount: 5, kicker: "Field I",
              notes: [("The outrun is pear-shaped",
                       "The dog leaves the handler's side and runs wide, opening out as it goes so that it comes in behind the sheep without ever showing itself to them from the front. A straight outrun lifts the sheep before the dog is behind them and the run is spoiled in the first twenty seconds."),
                      ("Why it must be wide",
                       "Sheep have a flight zone measured in yards on a quiet park field and in tens of yards on the open hill. A dog that cuts in inside that distance turns a settled group into a scatter.")]),
    FieldSpec(id: "nine_standards", name: "Nine Standards", place: "Yorkshire Dales",
              terrain: "Limestone pasture", breed: "Swaledale", sheepCount: 5, kicker: "Field II",
              notes: [("The lift",
                       "The moment the dog reaches the top of its outrun and the sheep first move. A good lift is almost invisible: the dog stands, the sheep lift their heads, and they walk off together. Everything after it is easier or harder because of it."),
                      ("Standing off",
                       "The dog is asked to stop short of the sheep and simply be present. Pressure without movement is the whole of the craft, and it is what separates a working dog from a keen one.")]),
    FieldSpec(id: "cwm_hirwaun", name: "Cwm Hirwaun", place: "Brecon", terrain: "Steep valley side",
              breed: "Welsh Mountain", sheepCount: 5, kicker: "Field III",
              notes: [("The balance point",
                       "The dog holds a position exactly opposite the direction you want the sheep to travel. Move the dog a little to one side of that line and the sheep swing the other way. Every command in a trial is really an adjustment of the balance point."),
                      ("Reading the eye",
                       "A collie with strong eye locks on and creeps; one with loose eye works upright and free. Strong eye holds a tight group and can jam on a stubborn ewe; loose eye moves a flock but may not hold a single.")]),
    FieldSpec(id: "glenfarg_brae", name: "Glenfarg Brae", place: "Perthshire", terrain: "Rolling brae",
              breed: "Scottish Blackface", sheepCount: 6, kicker: "Field IV",
              notes: [("Come bye and away to me",
                       "Come bye sends the dog clockwise round the sheep; away to me sends it anticlockwise. The words are old and the whistles that replace them are personal to each shepherd, but the two directions are the whole vocabulary of movement."),
                      ("Why whistles at all",
                       "A voice carries two hundred yards into wind on a bad day; a whistle carries the better part of a mile. On the hill the dog is often out of sight, and the whistle is the only thing that reaches it.")]),
    FieldSpec(id: "rhinog_bach", name: "Rhinog Bach", place: "Snowdonia", terrain: "Boulder and heather",
              breed: "Welsh Mountain", sheepCount: 5, kicker: "Field V",
              notes: [("The fetch line",
                       "From the lift the sheep should come in a straight line to the handler, through the fetch gates, and round the post. The judge is watching the line, not the speed: sheep off the line lose points from the moment they leave it."),
                      ("The gates",
                       "Seven yards wide at a national trial, set a fifth of the way down the fetch. Missing them costs, but wrenching the sheep round to make them costs more.")]),
    FieldSpec(id: "kirkstone_intake", name: "Kirkstone Intake", place: "Lakeland",
              terrain: "Walled intake", breed: "Herdwick", sheepCount: 5, kicker: "Field VI",
              notes: [("The drive",
                       "The hardest part of a trial: the sheep must be driven away from the handler in a straight line, then across, through two more sets of gates. Sheep want to come back to the handler and the dog must hold them off that pull the whole way."),
                      ("Cross-drive",
                       "The leg across the field in front of the handler, at right angles to the pull. Judges deduct for every yard the line bellies toward the post.")]),
    FieldSpec(id: "blacka_moor", name: "Blacka Moor", place: "Peak District", terrain: "Heather moor",
              breed: "Lonk", sheepCount: 5, kicker: "Field VII",
              notes: [("The shed",
                       "A ring is marked and two of the five sheep must be split off inside it, the dog coming through the gap the handler makes. It looks like nothing and it is where most runs are lost."),
                      ("Why sheep resist it",
                       "Splitting a flock is exactly what a flock exists to prevent. A sheep separated from the others will do almost anything to rejoin them, which is the force the dog is working against.")]),
    FieldSpec(id: "slieve_rushen", name: "Slieve Rushen", place: "Fermanagh", terrain: "Rushy hill",
              breed: "Cheviot", sheepCount: 5, kicker: "Field VIII",
              notes: [("The pen",
                       "A hurdle pen with a gate and a six-foot rope. The handler holds the rope and may not let go of it, so the dog does the work and the handler is a post that can lean."),
                      ("The last thirty seconds",
                       "Most pens are lost by hurrying. A dog that walks the sheep in slowly, one step at a time, will beat a faster dog that pushes them past the mouth.")]),
]

let fieldBookB: [FieldSpec] = [
    FieldSpec(id: "dunveth_downs", name: "Dunveth Downs", place: "Cornwall", terrain: "Coastal down",
              breed: "Dartmoor Greyface", sheepCount: 6, kicker: "Field IX",
              notes: [("Points and time",
                       "A national course carries a hundred points: outrun twenty, lift ten, fetch twenty, drive thirty, shed ten, pen ten. A run has fifteen minutes, and the whistle at the end stops everything where it stands."),
                      ("Deductions",
                       "Points are taken off, never added on. The judge starts at a hundred and every yard off the line, every stop the dog ignores and every sheep that breaks costs something.")]),
    FieldSpec(id: "sourhope_head", name: "Sourhope Head", place: "Cheviots", terrain: "Long grass slope",
              breed: "Cheviot", sheepCount: 5, kicker: "Field X",
              notes: [("Grip",
                       "A dog that takes hold of a sheep with its teeth is disqualified on the spot, whatever the provocation. The whole breed exists on the understanding that the threat is enough."),
                      ("The threat is the tool",
                       "A collie works sheep with the same movements a wolf uses to cut one out of a herd, stopped one step short. Everything the dog does is a promise it never keeps.")]),
    FieldSpec(id: "gowbarrow", name: "Gowbarrow Park", place: "Ullswater", terrain: "Parkland and bracken",
              breed: "Rough Fell", sheepCount: 5, kicker: "Field XI",
              notes: [("Park sheep and hill sheep",
                       "Sheep off a park field are used to people and will let a dog close. Hill sheep are not, and will run at the first sight of one at three hundred yards. The same dog needs two different distances."),
                      ("Reading them in the first ten seconds",
                       "How the sheep stand when the dog appears tells you which kind you have. Everything about the run is decided by whether you believe them.")]),
    FieldSpec(id: "trawsfynydd", name: "Trawsfynydd Moor", place: "Gwynedd", terrain: "Wet moor",
              breed: "Welsh Mountain", sheepCount: 6, kicker: "Field XII",
              notes: [("Lie down",
                       "The single most useful command there is. A dog lying down takes all the pressure off the sheep instantly, and a dog that will not lie down on a whistle cannot be trusted at distance."),
                      ("Steady",
                       "Between full speed and flat on the ground there is a walk, and a young dog learns it last. Most bad runs are a fast dog and a handler who only knows two speeds.")]),
    FieldSpec(id: "wanlockhead", name: "Wanlockhead", place: "Lowther Hills", terrain: "High bare hill",
              breed: "Scottish Blackface", sheepCount: 5, kicker: "Field XIII",
              notes: [("Wind and sound",
                       "Whistling into a hill wind loses you a third of your distance. Handlers learn to send a dog on the side of the field where the wind will carry, and to trust it out of hearing on the other."),
                      ("The dog casts on its own",
                       "At the far end of a hill gather the dog is beyond command and works from training and judgement. A trial course is a compressed picture of that, watched from one spot.")]),
    FieldSpec(id: "carn_dubh", name: "Carn Dubh", place: "Aberdeenshire", terrain: "Granite and rush",
              breed: "Scottish Blackface", sheepCount: 5, kicker: "Field XIV",
              notes: [("Old Hemp",
                       "Every border collie alive descends from one dog born in Northumberland in 1893, who worked with a quiet, upright style that beat everything and was bred from until it became the breed."),
                      ("Bred for work only",
                       "The registry is a working register: dogs are entered on what they do, not on how they look, which is why no two border collies look alike and all of them move the same way.")]),
    FieldSpec(id: "longmynd", name: "Longmynd Hollow", place: "Shropshire", terrain: "Dry heath",
              breed: "Beulah Speckled Face", sheepCount: 5, kicker: "Field XV",
              notes: [("The single",
                       "In a championship the shed becomes a single: one named sheep taken off the other fifteen and held. It is the hardest ten points in the sport."),
                      ("Holding after the shed",
                       "Taking the sheep off is half of it. The dog must then keep it apart, on its own, against everything the animal wants, until the judge is satisfied.")]),
    FieldSpec(id: "grasslees", name: "Grasslees Burn", place: "Redesdale", terrain: "Burn and haugh",
              breed: "Cheviot", sheepCount: 6, kicker: "Field XVI",
              notes: [("Water and gates",
                       "Sheep will not walk into water they cannot see the bottom of, and will follow a wall to a gate rather than cross a gap. A shepherd works with these habits rather than against them."),
                      ("The pull",
                       "Every field has a direction sheep want to go: toward the gate they came in by, toward the rest of the flock, toward home. Trials are set so that the pull works against the course.")]),
]

let fieldBookC: [FieldSpec] = [
    FieldSpec(id: "loch_skerrow", name: "Loch Skerrow", place: "Galloway", terrain: "Bog and knowes",
              breed: "Blackface", sheepCount: 5, kicker: "Field XVII",
              notes: [("Sheep see almost all the way round",
                       "A sheep's eye gives it about three hundred degrees of vision with a blind spot directly behind. A dog working in that blind spot pushes hard; a dog in view at the shoulder turns them."),
                      ("Depth and shadow",
                       "They see depth poorly and shadow as a hole. A dark gateway, a drain, a change of surface: all of them stop a flock that a shepherd expected to walk straight on.")]),
    FieldSpec(id: "hafod_y_llan", name: "Hafod y Llan", place: "Nant Gwynant", terrain: "Mountain ffridd",
              breed: "Welsh Mountain", sheepCount: 6, kicker: "Field XVIII",
              notes: [("Heft",
                       "Hill sheep are hefted: they know one patch of unfenced mountain and stay on it, and they teach it to their lambs. A hefted flock is knowledge that cannot be bought, only inherited."),
                      ("What that means for a gather",
                       "The shepherd is not driving strangers off a hill; he is collecting groups that each belong to a place, in an order that has been the same for two centuries.")]),
    FieldSpec(id: "whitfield_fell", name: "Whitfield Fell", place: "Pennines", terrain: "Rough grazing",
              breed: "Swaledale", sheepCount: 5, kicker: "Field XIX",
              notes: [("The nursery trial",
                       "Young dogs run a shortened course in winter, and a dog that will not stop or will not leave its handler is simply not entered. Trials began as a way of judging breeding stock in public."),
                      ("The first trial",
                       "Bala in Wales, 1873, ten dogs and three sheep, watched by three hundred people. The course has changed very little since.")]),
    FieldSpec(id: "eskdale_green", name: "Eskdale Green", place: "Cumbria", terrain: "Valley meadow",
              breed: "Herdwick", sheepCount: 5, kicker: "Field XX",
              notes: [("Herdwicks",
                       "Born black, greying to a hard slate as they age, and famous for coming back to their heft over any obstacle. They are the reason Lakeland fells look the way they do."),
                      ("Slow to move",
                       "A Herdwick will stand and look at a dog that would send a Cheviot half a mile. The pressure has to be held longer and released sooner.")]),
    FieldSpec(id: "achnasheen", name: "Achnasheen Bank", place: "Wester Ross", terrain: "Peat hag",
              breed: "Blackface", sheepCount: 6, kicker: "Field XXI",
              notes: [("Broken ground",
                       "In peat hags the dog disappears for whole seconds at a time. The handler whistles to where the dog should be, not to where it was last seen."),
                      ("Trusting the dog",
                       "There is a point in every hill gather where commands stop being useful. Good handlers stop whistling at that point; poor ones do not.")]),
    FieldSpec(id: "cregneash", name: "Cregneash Common", place: "Isle of Man", terrain: "Sea-blown common",
              breed: "Manx Loaghtan", sheepCount: 5, kicker: "Field XXII",
              notes: [("Horned sheep",
                       "Four horns on some Loaghtans, and a temperament to match. Horned breeds face a dog rather than turn from it, and a young dog learns fast which is which."),
                      ("Facing up",
                       "A ewe with a lamb will stamp and face the dog. The dog must hold its ground without moving in, and if it backs off once it will be tested every time after.")]),
    FieldSpec(id: "foel_grach", name: "Foel Grach Pastures", place: "Carneddau", terrain: "High pasture",
              breed: "Welsh Mountain", sheepCount: 6, kicker: "Field XXIII",
              notes: [("That'll do",
                       "The command that ends everything: the dog leaves the sheep and comes back. A dog that will not take it at the end of a hard day is a dog that will not last."),
                      ("Working out a life",
                       "A collie works perhaps ten seasons. The training that takes two years is spent in the first six months of the third, and the rest is the dog teaching the shepherd.")]),
    FieldSpec(id: "hound_tor", name: "Hound Tor Down", place: "Dartmoor", terrain: "Granite clitter",
              breed: "Dartmoor Greyface", sheepCount: 5, kicker: "Field XXIV",
              notes: [("The judge's card",
                       "Every section is written down as it happens, with the deductions marked against it. The card, not the crowd, decides the run, and a handler reads his own card afterwards to learn anything."),
                      ("What good looks like",
                       "Quiet sheep walking a straight line, a dog you barely notice, and a handler who has hardly whistled. A run that looks dull from the fence is usually the one that wins.")]),
]
